Ace_crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from crm.views import auth

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', auth.login, name='login'),
    url(r'^index/', auth.index, name='index'),
    url(r'^reg/', auth.reg, name='reg'),

    url(r'crm/', include('crm.urls')),
    url(r'rbac/', include('rbac.urls', namespace='rbac'))
]

crm/urls.py
from django.conf.urls import url, include

from crm.views import customer
from crm.views import consult
from crm.views import enrollment
from crm.views import teacher

urlpatterns = [
    # 公户
    # url(r'customer_list/', customer.customer_list, name='customer_list'),
    url(r'customer_list/', customer.CustomerList.as_view(), name='customer_list'),

    # 私户
    # url(r'my_customer/', customer.customer_list, name='my_customer'),
    url(r'my_customer/', customer.CustomerList.as_view(), name='my_customer'),

    # 增加客户
    url(r'add_customer/', customer.add_customer, name='add_customer'),
    # url(r'add_customer/', customer.customer_change, name='add_customer'),

    # 编辑客户
    url(r'edit_customer/(\d+)/', customer.edit_customer, name='edit_customer'),
    # url(r'edit_customer/(\d+)/', customer.customer_change, name='edit_customer'),

    # 展示跟进记录
    url(r'consult_list/(0)/', consult.ConsultList.as_view(), name='all_consult_list'),
    url(r'consult_list/(?P<customer_id>\d+)/', consult.ConsultList.as_view(), name='consult_list'),

    # 增加跟进
    url(r'add_consult/', consult.add_consult, name='add_consult'),

    # 编辑跟进
    url(r'edit_consult/(\d+)/', consult.edit_consult, name='edit_consult'),

    # 展示报名记录
    url(r'enrollment_list/', enrollment.EnrollmentList.as_view(), name='enrollment_list'),

    # 增加报名记录
    url(r'add_enrollment/(?P<customer_id>\d+)', enrollment.enrollment_change, name='add_enrollment'),

    # 编辑报名记录
    url(r'edit_enrollment/(?P<enrollment_id>\d+)/', enrollment.enrollment_change, name='edit_enrollment'),

    # 展示班级
    url(r'class_list/', teacher.ClassList.as_view(), name='class_list'),

    # 增加班级
    url(r'add_class/', teacher.class_change, name='add_class'),

    # 编辑班级
    url(r'edit_class/(\d+)/', teacher.class_change, name='edit_class'),

    # 展示课程记录
    url(r'course_record_list/(?P<class_id>\d+)/', teacher.CourseRecordList.as_view(), name='course_record_list'),

    # 增加课程记录
    url(r'add_course_record/(?P<class_id>\d+)', teacher.course_record_change, name='add_course_record'),

    # 编辑课程记录
    url(r'edit_course_record/(?P<record_id>\d+)', teacher.course_record_change, name='edit_course_record'),

    # 展示学习记录
    url(r'study_record_list/(?P<course_record_id>\d+)/', teacher.study_record_list, name='study_record_list'),

]

crm/utils/urls.py
from django.urls import reverse


def reverse_url(request, name, *args, **kwargs):
    # ?next=/crm/customer_list/?query=1&page=2
    next = request.GET.get('next')
    if next:
        return next
    else:
        return reverse(name, args=args, kwargs=kwargs)

crm/models.py
from django.db import models
from django.utils.safestring import mark_safe
from rbac.models import User



source_type = (('qq', "qq群"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('others', "其它"),)







class Department(models.Model):
    """
    部门表
    """
    name = models.CharField(max_length=32, verbose_name="部门名称")
    count = models.IntegerField(verbose_name="人数", default=0)


class UserProfile(User,models.Model):
    """
    用户表
    """
    username = models.EmailField(max_length=255, unique=True, )
    password = models.CharField(max_length=128, verbose_name='密码')
    name = models.CharField('名字', max_length=32)
    department = models.ForeignKey('Department', default=None, blank=True, null=True)
    mobile = models.CharField('手机', max_length=32, default=None, blank=True, null=True)
    memo = models.TextField('备注', blank=True, null=True, default=None)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Customer(models.Model):
    """
    客户表
    """

    name = models.CharField('姓名', max_length=32, blank=True, null=True,)
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    date = models.DateTimeField("咨询日期", auto_now_add=True)
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    network_consultant = models.ForeignKey('UserProfile', blank=True, null=True, verbose_name='咨询师',
                                           related_name='network_consultant')
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True, )

    def __str__(self):
        return "{}".format( self.name)



class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8,  help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)




class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型",  max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    customer = models.ForeignKey('Customer', verbose_name="客户")
    consultant = models.ForeignKey('UserProfile', verbose_name="销售")
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True)

crm/forms.py
from django import forms
from crm import models
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

import hashlib


class BSForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for filed in self.fields.values():
            if not isinstance(filed, forms.BooleanField):
                filed.widget.attrs.update({'class': "form-control"})


class RegForm(BSForm):
    password = forms.CharField(widget=forms.PasswordInput, min_length=6, label='密码')
    re_pwd = forms.CharField(widget=forms.PasswordInput, label='确认密码')

    class Meta:
        model = models.UserProfile
        fields = '__all__'  # ['username','password']
        exclude = ['memo', 'is_active']
        labels = {
            'username': '用户名'
        }
        widgets = {
            'password': forms.PasswordInput(attrs={'class': "form-control", 'k1': 'v1'}),
        }
        error_messages = {
            'password': {
                'required': '必填的'
            }
        }

    def clean(self):
        pwd = self.cleaned_data.get('password', '')
        re_pwd = self.cleaned_data.get('re_pwd', '')
        if pwd == re_pwd:
            md5 = hashlib.md5()
            md5.update(pwd.encode('utf-8'))
            pwd = md5.hexdigest()
            self.cleaned_data['password'] = pwd
            return self.cleaned_data
        self.add_error('re_pwd', '两次密码不一致')

        raise ValidationError('两次密码不一直')


class CustomerForm(BSForm):
    class Meta:
        model = models.Customer
        fields = "__all__"
        # exclude = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].widget.attrs.pop('class')


class ConsultForm(BSForm):

    class Meta:
        model = models.ConsultRecord
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


        print(self.instance)  # obj = models.ConsultRecord(consultant=request.uer_obj)
        print(self.instance.consultant.customers.all())
        customer_chioices = [(customer.pk, str(customer)) for customer in self.instance.consultant.customers.all()]
        customer_chioices.insert(0, ('', '----------'))
        self.fields['customer'].choices = customer_chioices

        self.fields['consultant'].choices = [(self.instance.consultant.pk, self.instance.consultant), ]


class EnrollmentForm(BSForm):
    class Meta:
        model = models.Enrollment
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


        self.fields['customer'].choices = [(self.instance.customer.pk, self.instance.customer)]

        self.fields['enrolment_class'].choices = [(i.pk, str(i)) for i in self.instance.customer.class_list.all()]


class ClassForm(BSForm):
    class Meta:
        model = models.ClassList
        fields = '__all__'


class CourseRecordForm(BSForm):
    class Meta:
        model = models.CourseRecord
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 限制当前的班级是跳转过来的班级
        self.fields['re_class'].choices = [(self.instance.re_class.pk, self.instance.re_class)]
        # 限制老师是当前的用户
        self.fields['teacher'].choices = [(self.instance.teacher.pk, self.instance.teacher), ]


class StudyRecordForm(BSForm):
    class Meta:
        model = models.StudyRecord
        fields = '__all__'

crm/views/consult.py
from django.shortcuts import render, redirect, HttpResponse, reverse
from crm import models
from crm.forms import ConsultForm
from django.http.request import QueryDict
from crm.utils.pagination import Pagination

from crm.utils.urls import reverse_url

from django.views import View
from django.db.models import Q


# 展示跟进
class ConsultList(View):

    def get(self, request, customer_id):

        q = self.search([])

        if customer_id == '0':
            all_consult = models.ConsultRecord.objects.filter(q, delete_status=False,
                                                              consultant=request.user_obj).order_by('-date')
        else:
            all_consult = models.ConsultRecord.objects.filter(q, delete_status=False, customer_id=customer_id,
                                                              consultant=request.user_obj).order_by('-date')

        page = Pagination(request.GET.get('page'), all_consult.count(), request.GET.copy(),10)
        return render(request, 'consultant/consult_list.html',
                      {'all_consult': all_consult[page.start:page.end], 'page_html': page.page_html}, )

    def post(self, request, customer_id):

        action = request.POST.get('action')

        if not hasattr(self, action):
            return HttpResponse('非法操作')

        getattr(self, action)()

        return self.get(request,customer_id)

    def search(self, filed_list):
        query = self.request.GET.get('query', '')
        q = Q()
        q.connector = 'OR'
        for field in filed_list:
            # q.children.append(Q(qq__contains=query))
            q.children.append(Q(('{}__contains'.format(field), query)))
        return q


# 增加跟进
def add_consult(request):
    obj = models.ConsultRecord(consultant=request.user_obj)

    form_obj = ConsultForm(instance=obj)
    if request.method == 'POST':
        form_obj = ConsultForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()

            return redirect(reverse_url(request, 'consult_list'))

    return render(request, 'consultant/add_consult.html', {'form_obj': form_obj})


def edit_consult(request, edit_id):
    obj = models.ConsultRecord.objects.filter(pk=edit_id).first()

    form_obj = ConsultForm(instance=obj)
    if request.method == 'POST':
        form_obj = ConsultForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()

            return redirect(reverse_url(request, 'consult_list'))

    return render(request, 'consultant/edit_consult.html', {'form_obj': form_obj})

crm/views/customer.py
from django.shortcuts import render, redirect, HttpResponse, reverse
from crm import models
from crm.forms import CustomerForm
from django.http.request import QueryDict
from crm.utils.pagination import Pagination
from crm.utils.urls import reverse_url
from django.db import transaction

# def customer_list(request):
#     if request.path_info == reverse('customer_list'):
#         all_customer = models.Customer.objects.filter(consultant__isnull=True)
#     else:
#         all_customer = models.Customer.objects.filter(consultant=request.user_obj)
#
#     return render(request, 'customer_list.html', {'all_customer': all_customer})

from django.views import View
from django.db.models import Q
from django.conf import settings, global_settings


class CustomerList(View):

    def get(self, request):
        # query = request.GET.get('query', '')
        # 'django.http.request.QueryDict'
        # dic = request.GET
        # dic._mutable = True
        # dic['page'] = 1
        # print(dic)

        q = self.search(['qq', 'name', ])

        if request.path_info == reverse('customer_list'):
            all_customer = models.Customer.objects.filter(q, consultant__isnull=True, )
        else:
            all_customer = models.Customer.objects.filter(q, consultant=request.user_obj)

        page = Pagination(request.GET.get('page'), all_customer.count(), request.GET.copy(), 10)
        return render(request, 'consultant/customer_list.html',
                      {'all_customer': all_customer[page.start:page.end], 'page_html': page.page_html}, )

    def post(self, request):

        action = request.POST.get('action')

        if not hasattr(self, action):
            return HttpResponse('非法操作')

        ret = getattr(self, action)()
        if ret:
            return ret

        return self.get(request)

    def multi_apply(self):
        # 公户变私户
        ids = self.request.POST.getlist('ids')
        # 方式一
        # models.Customer.objects.filter(pk__in=ids).update(consultant=self.request.user_obj)

        # 当前销售私户的数量   +  申请的客户的数量   > 上限
        if self.request.user_obj.customers.all().count() + len(ids) > settings.MAX_CUSTOMER_NUM:
            return HttpResponse('做人不要太贪心了，给别人留点')

        # 开启事务：
        with transaction.atomic():
            queryset = models.Customer.objects.filter(pk__in=ids, consultant__isnull=True).select_for_update()  # 加行锁
            # 跟新
            # 判断提交的数据数  和 查询的数据数
            if len(ids) == queryset.count():
                queryset.update(consultant=self.request.user_obj)
                return
            return HttpResponse('你的手速太慢，已经别别人掳走了')

        # 方式二
        # self.request.user_obj.customers.add(*models.Customer.objects.filter(pk__in=ids))

    def multi_pub(self):
        # 私户变公户
        ids = self.request.POST.getlist('ids')
        # 方式一
        # models.Customer.objects.filter(pk__in=ids).update(consultant=None)

        # 方式二
        self.request.user_obj.customers.remove(*models.Customer.objects.filter(pk__in=ids))

    def search(self, filed_list):
        query = self.request.GET.get('query', '')
        # q = Q(Q(qq__contains=query) | Q(name__contains=query))
        q = Q()
        q.connector = 'OR'
        for field in filed_list:
            # q.children.append(Q(qq__contains=query))
            q.children.append(Q(('{}__contains'.format(field), query)))
        return q


def add_customer(request):
    # 创建一个没有数据的Form
    form_obj = CustomerForm()

    if request.method == 'POST':
        # 创建一个包含提交数据的Form
        form_obj = CustomerForm(request.POST)
        # 对数据进行校验
        if form_obj.is_valid():
            form_obj.save()  # 新增

            return redirect(reverse_url(request, 'customer_list'))

    return render(request, 'consultant/add_customer.html', {'form_obj': form_obj})


def edit_customer(request, edit_id):
    obj = models.Customer.objects.filter(pk=edit_id).first()

    form_obj = CustomerForm(instance=obj)

    if request.method == 'POST':
        # 有修改的数据和原始的数据
        form_obj = CustomerForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()

            return redirect(reverse_url(request, 'customer_list'))

    return render(request, 'consultant/edit_customer.html', {'form_obj': form_obj})


# 新增和编辑客户
def customer_change(request, edit_id=None):
    obj = models.Customer.objects.filter(pk=edit_id).first()
    form_obj = CustomerForm(instance=obj)

    title = '编辑客户' if edit_id else '新增客户'
    if request.method == 'POST':
        # 有修改的数据和原始的数据
        form_obj = CustomerForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()

            return redirect(reverse('customer_list'))

    return render(request, 'consultant/customer_change.html', {'form_obj': form_obj, 'title': title})

crm/templates/consultant/add_consult.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default" style="margin: 15px">
        <div class="panel-heading">
            <h3 class="panel-title">添加跟进</h3>
        </div>
        <div class="panel-body">


            <div class="col-lg-8 col-lg-offset-2">
                <form class="form-horizontal" action="" method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form_obj %}

                        <div class="form-group  {% if field.errors %} has-error {% endif %} ">


                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-2 control-label">{{ field.label }}</label>
                            <div class="col-sm-10">
                                {{ field }}
                                <span class="help-block"> {{ field.errors.0 }}</span>
                            </div>
                        </div>

                    {% endfor %}


                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">增加</button>
                        </div>
                    </div>
                </form>
            </div>


        </div>
    </div>


{% endblock %}

crm/templates/consultant/add_customer.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default" style="margin: 15px">
        <div class="panel-heading">
            <h3 class="panel-title">添加客户</h3>
        </div>
        <div class="panel-body">


            <div class="col-lg-8 col-lg-offset-2">
                <form class="form-horizontal" action="" method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form_obj %}

                        <div class="form-group  {% if field.errors %} has-error {% endif %} ">


                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-2 control-label">{{ field.label }}</label>
                            <div class="col-sm-10">
                                {{ field }}
                                <span class="help-block"> {{ field.errors.0 }}</span>
                            </div>
                        </div>

                    {% endfor %}


                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">增加</button>
                        </div>
                    </div>
                </form>
            </div>


        </div>
    </div>


{% endblock %}

crm/templates/consultant/consult_list.html
{% extends 'layout.html' %}

{% block content %}
    {% load my_tags %}

    <div class="panel panel-default" style="margin: 15px">
        <div class="panel-heading">
            <h3 class="panel-title">展示跟进记录</h3>
        </div>
        <div class="panel-body">
            <div>
                <a class="btn btn-sm btn-primary" style="margin-bottom: 5px"
                   href="{% reverse_url request 'add_consult' %}">添加</a>

            </div>
            <form action="" class="form-inline pull-right">
                <input type="text" name="query" class="form-control">
                <button class="btn btn-sm btn-primary">搜索</button>
            </form>


            <form action="" method="post" class="form-inline">
                {% csrf_token %}

                <select name="action" id="" class="form-control">

                    <option value="multi_del">批量删除</option>
                </select>
                <button class="btn btn-sm btn-primary">提交</button>

                <table class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>选择</th>
                        <th>客户</th>
                        <th>跟进内容</th>
                        <th>状态</th>
                        <th>跟进人</th>
                        <th>日期</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for consult in all_consult %}
                        <tr>
                            <td>
                                <input type="checkbox" value="{{ customer.pk }}" name="ids">
                            </td>
                            <td>{{ consult.customer.name }}</td>
                            <td>{{ consult.note }}</td>
                            <td>{{ consult.get_status_display }}</td>
                            <td>{{ consult.consultant }}</td>
                            <td>{{ consult.date }}</td>
                            <td>
                                <a href="{% reverse_url request 'edit_consult' consult.pk %}"><i
                                        class="fa fa-pencil-square-o"></i></a>
                            </td>

                        </tr>

                    {% endfor %}


                    </tbody>
                </table>
            </form>
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {{ page_html }}
                </ul>
            </nav>
        </div>
    </div>

{% endblock %}

crm/templates/consultant/customer_change.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default" style="margin: 15px">
        <div class="panel-heading">
            <h3 class="panel-title">

                {{ title }}
            </h3>
        </div>
        <div class="panel-body">


            <div class="col-lg-8 col-lg-offset-2">
                <form class="form-horizontal" action="" method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form_obj %}

                        <div class="form-group  {% if field.errors %} has-error {% endif %} ">


                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-2 control-label">{{ field.label }}</label>
                            <div class="col-sm-10">
                                {{ field }}
                                <span class="help-block"> {{ field.errors.0 }}</span>
                            </div>
                        </div>

                    {% endfor %}


                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">保存</button>
                        </div>
                    </div>
                </form>
            </div>


        </div>
    </div>


{% endblock %}

crm/templates/consultant/customer_list.html
{% extends 'layout.html' %}

{% block content %}
    {% load my_tags %}

    <div class="panel panel-default" style="margin: 15px">
        <div class="panel-heading">
            <h3 class="panel-title">展示客户</h3>
        </div>
        <div class="panel-body">
            <div>
                {% load rbac %}
                {% if request|has_permission:'add_customer' %}
                    <a class="btn btn-sm btn-primary" style="margin-bottom: 5px"
                       href="{% reverse_url request 'add_customer' %}">添加</a>

                {% endif %}

            </div>
            <form action="" class="form-inline pull-right">
                <input type="text" name="query" class="form-control">
                <button class="btn btn-sm btn-primary">搜索</button>
            </form>


            <form action="" method="post" class="form-inline">
                {% csrf_token %}

                <select name="action" id="" class="form-control">

                    {% if request.path_info == '/crm/customer_list/' %}
                        <option value="multi_apply">公户变私户</option>
                    {% else %}
                        <option value="multi_pub">私户变公户</option>
                    {% endif %}


                    <option value="multi_del">批量删除</option>
                </select>
                <button class="btn btn-sm btn-primary">提交</button>

                <table class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>选择</th>
                        <th>序号</th>
                        <th>QQ</th>
                        <th>姓名</th>
                        <th>性别</th>
                        {#                    <th>出生日期</th>#}
                        <th>客户来源</th>
                        <th>咨询课程</th>
                        <th>状态</th>
                        <th>咨询日期</th>
                        <th>销售</th>
                        <th>已报班级</th>
                        <th>跟进记录</th>
                        <th>报名</th>
                        {% if request|has_permission:'edit_customer' %}
                            <th>操作</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>

                    {% for customer in all_customer %}
                        <tr>
                            <td>
                                <input type="checkbox" value="{{ customer.pk }}" name="ids">
                            </td>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ customer.qq }}</td>
                            <td>{{ customer.name|default:'未填写' }}</td>
                            <td>{{ customer.get_sex_display }}</td>
                            {#                        <td>{{ customer.birthday }}</td>#}
                            <td>{{ customer.source }}</td>
                            <td>{{ customer.course }}</td>
                            <td>
                                {{ customer.show_status }}
                            </td>
                            <td>{{ customer.date }}</td>
                            <td>{{ customer.consultant.name }}</td>
                            <td>{{ customer.show_class }}</td>
                            <td><a href="{% url 'consult_list' customer.pk %}">查看</a></td>
                            <td><a href="{% url 'add_enrollment' customer.pk %}">添加</a></td>

                            {% if request|has_permission:'edit_customer' %}
                                <td>
                                    {#                                <a href="{% url 'edit_customer' customer.pk %}"><i#}
                                    {#                                        class="fa fa-pencil-square-o"></i></a>#}
                                    <a href="{% reverse_url request 'edit_customer' customer.pk %}"><i
                                            class="fa fa-pencil-square-o"></i></a>
                                </td>
                            {% endif %}

                        </tr>

                    {% endfor %}


                    </tbody>
                </table>
            </form>
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {{ page_html }}
                </ul>
            </nav>
        </div>
    </div>

{% endblock %}

crm/templates/consultant/edit_consult.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default" style="margin: 15px">
        <div class="panel-heading">
            <h3 class="panel-title">编辑跟进</h3>
        </div>
        <div class="panel-body">


            <div class="col-lg-8 col-lg-offset-2">
                <form class="form-horizontal" action="" method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form_obj %}

                        <div class="form-group  {% if field.errors %} has-error {% endif %} ">


                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-2 control-label">{{ field.label }}</label>
                            <div class="col-sm-10">
                                {{ field }}
                                <span class="help-block"> {{ field.errors.0 }}</span>
                            </div>
                        </div>

                    {% endfor %}


                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">保存</button>
                        </div>
                    </div>
                </form>
            </div>


        </div>
    </div>


{% endblock %}

crm/templates/consultant/edit_customer.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default" style="margin: 15px">
        <div class="panel-heading">
            <h3 class="panel-title">编辑客户</h3>
        </div>
        <div class="panel-body">


            <div class="col-lg-8 col-lg-offset-2">
                <form class="form-horizontal" action="" method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form_obj %}

                        <div class="form-group  {% if field.errors %} has-error {% endif %} ">


                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-2 control-label">{{ field.label }}</label>
                            <div class="col-sm-10">
                                {{ field }}
                                <span class="help-block"> {{ field.errors.0 }}</span>
                            </div>
                        </div>

                    {% endfor %}


                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">保存</button>
                        </div>
                    </div>
                </form>
            </div>


        </div>
    </div>


{% endblock %}