Ace_crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from crm.views import auth

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', auth.login, name='login'),
    url(r'^index/', auth.index, name='index'),
    url(r'^reg/', auth.reg, name='reg'),

    url(r'crm/', include('crm.urls')),
    url(r'rbac/', include('rbac.urls', namespace='rbac'))
]

crm/urls.py
from django.conf.urls import url, include

from crm.views import customer
from crm.views import consult
from crm.views import enrollment
from crm.views import teacher

urlpatterns = [
    # 公户
    # url(r'customer_list/', customer.customer_list, name='customer_list'),
    url(r'customer_list/', customer.CustomerList.as_view(), name='customer_list'),

    # 私户
    # url(r'my_customer/', customer.customer_list, name='my_customer'),
    url(r'my_customer/', customer.CustomerList.as_view(), name='my_customer'),

    # 增加客户
    url(r'add_customer/', customer.add_customer, name='add_customer'),
    # url(r'add_customer/', customer.customer_change, name='add_customer'),

    # 编辑客户
    url(r'edit_customer/(\d+)/', customer.edit_customer, name='edit_customer'),
    # url(r'edit_customer/(\d+)/', customer.customer_change, name='edit_customer'),

    # 展示跟进记录
    url(r'consult_list/(0)/', consult.ConsultList.as_view(), name='all_consult_list'),
    url(r'consult_list/(?P<customer_id>\d+)/', consult.ConsultList.as_view(), name='consult_list'),

    # 增加跟进
    url(r'add_consult/', consult.add_consult, name='add_consult'),

    # 编辑跟进
    url(r'edit_consult/(\d+)/', consult.edit_consult, name='edit_consult'),

    # 展示报名记录
    url(r'enrollment_list/', enrollment.EnrollmentList.as_view(), name='enrollment_list'),

    # 增加报名记录
    url(r'add_enrollment/(?P<customer_id>\d+)', enrollment.enrollment_change, name='add_enrollment'),

    # 编辑报名记录
    url(r'edit_enrollment/(?P<enrollment_id>\d+)/', enrollment.enrollment_change, name='edit_enrollment'),

    # 展示班级
    url(r'class_list/', teacher.ClassList.as_view(), name='class_list'),

    # 增加班级
    url(r'add_class/', teacher.class_change, name='add_class'),

    # 编辑班级
    url(r'edit_class/(\d+)/', teacher.class_change, name='edit_class'),

    # 展示课程记录
    url(r'course_record_list/(?P<class_id>\d+)/', teacher.CourseRecordList.as_view(), name='course_record_list'),

    # 增加课程记录
    url(r'add_course_record/(?P<class_id>\d+)', teacher.course_record_change, name='add_course_record'),

    # 编辑课程记录
    url(r'edit_course_record/(?P<record_id>\d+)', teacher.course_record_change, name='edit_course_record'),

    # 展示学习记录
    url(r'study_record_list/(?P<course_record_id>\d+)/', teacher.study_record_list, name='study_record_list'),

]

rbac/urls.py
from django.conf.urls import url
from rbac import views

urlpatterns = [

    url(r'^role/list/$', views.role_list, name='role_list'),
    url(r'^role/add/$', views.role_change, name='role_add'),
    url(r'^role/edit/(\d+)/$', views.role_change, name='role_edit'),
    url(r'^role/del/(\d+)/$', views.role_del, name='role_del'),

    url(r'^menu/list/$', views.menu_list, name='menu_list'),
    url(r'^menu/add/$', views.menu_change, name='menu_add'),
    url(r'^menu/edit/(\d+)/$', views.menu_change, name='menu_edit'),
    url(r'^(menu)/del/(\d+)/$', views.delete, name='menu_del'),


    url(r'^permission/add/$', views.permission_change, name='permission_add'),
    url(r'^permission/edit/(\d+)/$', views.permission_change, name='permission_edit'),
    url(r'^(permission)/del/(\d+)/$', views.delete, name='permission_del'),

    url(r'^multi/permissions/$', views.multi_permissions, name='multi_permissions'),

    url(r'^distribute/permissions/$', views.distribute_permissions, name='distribute_permissions'),

]

rbac/models.py
from django.db import models


class Menu(models.Model):
    """
    菜单表  一级菜单
    """
    name = models.CharField(max_length=32, verbose_name='名称')
    icon = models.CharField(max_length=56, verbose_name='图标', blank=True, null=True)
    weight = models.IntegerField(default=1, verbose_name='权重')

    def __str__(self):
        return self.name


class Permission(models.Model):
    """
    权限表
    menu_id
        有   表示当前的权限是二级菜单  也是父权限
        没有  就是一个普通的权限

    parent_id
        有    表示当前的权限是一个子权限
        没有  父权限

    """
    url = models.CharField(max_length=255, verbose_name='权限', unique=True)
    title = models.CharField(max_length=32, verbose_name='标题')
    name = models.CharField(max_length=32, verbose_name='URL别名', unique=True)
    menu = models.ForeignKey('Menu', blank=True, null=True, verbose_name='所属菜单')
    parent = models.ForeignKey('Permission', blank=True, null=True, verbose_name='父权限')

    def __str__(self):
        return self.title


class Role(models.Model):
    """
    角色表
    """
    name = models.CharField(max_length=32, verbose_name='角色名称')
    permissions = models.ManyToManyField('Permission', blank=True)

    def __str__(self):
        return self.name


class User(models.Model):
    """
    用户表
    """
    # name = models.CharField(max_length=32, verbose_name='用户名')
    # pwd = models.CharField(max_length=32, verbose_name='密码')
    roles = models.ManyToManyField(Role, blank=True)

    class Meta:
        abstract = True     # 执行数据库迁移命令时不会生成具体的表，这张表做基类

rbac/service/routes.py
from django.conf import settings
from django.utils.module_loading import import_string
from django.urls import RegexURLResolver, RegexURLPattern
from collections import OrderedDict


def recursion_urls(pre_namespace, pre_url, urlpatterns, url_ordered_dict):
    for item in urlpatterns:
        if isinstance(item, RegexURLResolver):
            if pre_namespace:
                if item.namespace:
                    namespace = "%s:%s" % (pre_namespace, item.namespace,)
                else:
                    namespace = pre_namespace
            else:
                if item.namespace:
                    namespace = item.namespace
                else:
                    namespace = None
            #   none  '/^'
            recursion_urls(namespace, pre_url + item.regex.pattern, item.url_patterns, url_ordered_dict)
        else:

            if pre_namespace:  #  web
                name = "%s:%s" % (pre_namespace, item.name,)   # web:login
            else:
                name = item.name
            if not item.name:
                raise Exception('URL路由中必须设置name属性')
            # /^^login/$   /login/
            url = pre_url + item._regex
            url_ordered_dict[name] = {'name': name, 'url': url.replace('^', '').replace('$', '')}


def get_all_url_dict(ignore_namespace_list=None):
    """
    获取路由中所有的URL
    :return:

    { url别名：{ 'name' :URL别名  url ：路径 }  }
    """
    ignore_list = ignore_namespace_list or []
    url_ordered_dict = OrderedDict()

    md = import_string(settings.ROOT_URLCONF)
    urlpatterns = []


    """
    [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('web.urls')),
    url(r'^rbac/', include('rbac.urls', namespace='rbac')),
    
    视图函数 ： RegexURLPattern
    inculde  : RegexURLResolver
    
    ]
    """
    for item in md.urlpatterns:
        if isinstance(item, RegexURLResolver) and item.namespace in ignore_list:
            continue
        urlpatterns.append(item)
    recursion_urls(None, "/", urlpatterns, url_ordered_dict)
    return url_ordered_dict

rbac/views.py
from django.shortcuts import render, redirect, reverse, HttpResponse
from rbac import models
from rbac.forms import RoleForm, MenuForm, PermissionForm, MultiPermissionForm
from crm.models import UserProfile

def role_list(request):
    all_roles = models.Role.objects.all()
    return render(request, 'rbac/role_list.html', {'all_roles': all_roles})


def role_change(request, edit_id=None):
    obj = models.Role.objects.filter(pk=edit_id).first()

    form_obj = RoleForm(instance=obj)
    if request.method == 'POST':
        form_obj = RoleForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            return redirect(reverse('rbac:role_list'))

    return render(request, 'rbac/form.html', {'form_obj': form_obj})


def role_del(request, del_id):
    models.Role.objects.filter(pk=del_id).delete()
    return redirect(reverse('rbac:role_list'))


from django.db.models import Q


def menu_list(request):
    all_menus = models.Menu.objects.all()

    mid = request.GET.get('mid')
    if mid:
        # all_permissions = models.Permission.objects.filter(menu_id=mid)
        all_permissions = models.Permission.objects.filter(Q(menu_id=mid) | Q(parent__menu_id=mid)).values()
    else:
        all_permissions = models.Permission.objects.all().values()

    permission_dict = {}

    for i in all_permissions:

        menu_id = i.get('menu_id')
        p_id = i.get('id')
        if menu_id:
            permission_dict[p_id] = i
            i['children'] = []

    for i in all_permissions:
        pid = i.get('parent_id')
        if pid:
            permission_dict[pid]['children'].append(i)

    print(permission_dict)

    return render(request, 'rbac/menu_list.html',
                  {'mid': mid, 'all_menus': all_menus, 'all_permissions': permission_dict})


def menu_change(request, edit_id=None):
    obj = models.Menu.objects.filter(pk=edit_id).first()

    form_obj = MenuForm(instance=obj)
    if request.method == 'POST':
        form_obj = MenuForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            return redirect(reverse('rbac:menu_list'))

    return render(request, 'rbac/form.html', {'form_obj': form_obj})


def permission_change(request, edit_id=None):
    obj = models.Permission.objects.filter(pk=edit_id).first()

    form_obj = PermissionForm(instance=obj)
    if request.method == 'POST':
        form_obj = PermissionForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            return redirect(reverse('rbac:menu_list'))

    return render(request, 'rbac/form.html', {'form_obj': form_obj})


def delete(request, table, del_id):
    model_class = getattr(models, table.capitalize())

    if model_class:
        model_class.objects.filter(pk=del_id).delete()
        return redirect(reverse('rbac:menu_list'))

    else:
        return HttpResponse('不能删除')


from django.forms import modelformset_factory, formset_factory
from rbac.service.routes import get_all_url_dict


def multi_permissions(request):
    """
    批量操作权限
    :param request:
    :return:
    """
    post_type = request.GET.get('type')

    # 编辑和删除
    FormSet = modelformset_factory(models.Permission, MultiPermissionForm, extra=0)
    # 新增
    AddFormSet = formset_factory(MultiPermissionForm, extra=0)

    # 数据库中所有的权限
    permissions = models.Permission.objects.all()
    # 路由系统中所有的URL  权限
    router_dict = get_all_url_dict(ignore_namespace_list=['admin', ])

    # 数据库中所有的权限的别名的集合
    permissions_name_set = set([i.name for i in permissions])

    # 路由系统中所有的权限的别名的集合
    router_name_set = set(router_dict.keys())
    # 新增权限的name_set
    add_name_set = router_name_set - permissions_name_set

    add_formset = AddFormSet(initial=[row for name, row in router_dict.items() if name in add_name_set])

    if request.method == 'POST' and post_type == 'add':
        add_formset = AddFormSet(request.POST)
        if add_formset.is_valid():
            permission_obj_list = [models.Permission(**i) for i in add_formset.cleaned_data]
            query_list = models.Permission.objects.bulk_create(permission_obj_list)
            add_formset = AddFormSet()
            for i in query_list:
                permissions_name_set.add(i.name)

    # 要删除的权限
    del_name_set = permissions_name_set - router_name_set
    del_formset = FormSet(queryset=models.Permission.objects.filter(name__in=del_name_set))

    update_name_set = permissions_name_set & router_name_set
    update_formset = FormSet(queryset=models.Permission.objects.filter(name__in=update_name_set))

    if request.method == 'POST' and post_type == 'update':
        update_formset = FormSet(request.POST)
        if update_formset.is_valid():
            update_formset.save()
            update_formset = FormSet(queryset=models.Permission.objects.filter(name__in=update_name_set))

    return render(
        request,
        'rbac/multi_permissions.html',
        {
            'del_formset': del_formset,
            'update_formset': update_formset,
            'add_formset': add_formset,
        }
    )


def distribute_permissions(request):
    """
    分配权限
    :param request:
    :return:
    """
    uid = request.GET.get('uid')
    rid = request.GET.get('rid')

    if request.method == 'POST' and request.POST.get('postType') == 'role':
        user = UserProfile.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        user.roles.set(request.POST.getlist('roles'))

    if request.method == 'POST' and request.POST.get('postType') == 'permission' and rid:
        role = models.Role.objects.filter(id=rid).first()
        if not role:
            return HttpResponse('角色不存在')
        role.permissions.set(request.POST.getlist('permissions'))

    # 所有的用户
    user_list = UserProfile.objects.all()

    # 当前用户所拥有角色
    user_has_roles = UserProfile.objects.filter(id=uid).values('id', 'roles')

    """
    用户所拥有的角色id
    user_has_roles_dict =  { 角色id : None  }
    """
    user_has_roles_dict = {item['roles']: None for item in user_has_roles}

    # 所有的角色
    role_list = models.Role.objects.all()

    if rid:
        role_has_permissions = models.Role.objects.filter(id=rid, permissions__id__isnull=False).values('id',
                                                                                                        'permissions')
    elif uid and not rid:
        # 当前的用户
        user = UserProfile.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        # 当前用户 所有有的角色和所有权限的id
        role_has_permissions = user.roles.filter(permissions__id__isnull=False).values('id', 'permissions')
        role_has_permissions = user.roles.filter(permissions__id__isnull=False).values('id', 'permissions')
    else:
        role_has_permissions = []

    # 当前用户所有的权限id
    """
    role_has_permissions_dict =  {    权限的ID ：None}
    """

    role_has_permissions_dict = {item['permissions']: None for item in role_has_permissions}

    all_menu_list = []

    queryset = models.Menu.objects.values('id', 'name')  # 【   {id   name   }】
    menu_dict = {}

    """
    all_menu_list = [   {id   name  children:[
        {  'id', 'title', 'menu_id'  children : [
             {'id', 'title', 'parent_id' }
        ]  }
    ]  } 
    
    ,{'id': None, 'title': '其他', 'children': [
         {'id', 'title', 'parent_id' }
    ]}]
    
    
    menu_dict = { 
            菜单的id:  {id   name  children:[
                {  'id', 'title', 'menu_id'  children : [
                     {'id', 'title', 'parent_id' }
                ]  }
            ]  } ,
            None:  {'id': None, 'title': '其他', 'children': [
             {'id', 'title', 'parent_id' }
            ]}
    }
    """

    for item in queryset:  # {id   name   }
        item['children'] = []  # {id   name  children:[]   }
        menu_dict[item['id']] = item
        all_menu_list.append(item)

    other = {'id': None, 'title': '其他', 'children': []}
    all_menu_list.append(other)
    menu_dict[None] = other

    # 所有的父权限
    root_permission = models.Permission.objects.filter(menu__isnull=False).values('id', 'title', 'menu_id')
    root_permission_dict = {}
    """
      root_permission_dict = {
            父权限的id :  {  'id', 'title', 'menu_id'  children : [  {'id', 'title', 'parent_id' } ]  }
      }
    """

    for per in root_permission:  # {  'id', 'title', 'menu_id' }
        per['children'] = []  # {  'id', 'title', 'menu_id'  children : []  }
        nid = per['id']
        menu_id = per['menu_id']
        root_permission_dict[nid] = per
        menu_dict[menu_id]['children'].append(per)

    # 可能是子权限
    node_permission = models.Permission.objects.filter(menu__isnull=True).values('id', 'title', 'parent_id')

    for per in node_permission:   # {'id', 'title', 'parent_id' }
        pid = per['parent_id']
        if not pid:
            menu_dict[None]['children'].append(per)
            continue
        root_permission_dict[pid]['children'].append(per)

    return render(
        request,
        'rbac/distribute_permissions.html',
        {
            'user_list': user_list,
            'role_list': role_list,
            'all_menu_list': all_menu_list,
            'user_has_roles_dict': user_has_roles_dict,
            'role_has_permissions_dict': role_has_permissions_dict,
            'uid': uid,
            'rid': rid
        }
    )

rbac/templates/rbac/breadcrumb.html
<div>
    <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">

        {% for breadcrumb in breadcrumb_list %}
            {% if forloop.last %}
                <li class="active">{{ breadcrumb.title }}</li>
            {% else %}
                <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.title }}</a></li>

            {% endif %}
        {% endfor %}

    </ol>
</div>

rbac/templates/rbac/form.html
{% extends 'layout.html' %}

{% block css %}
    <style>
        .icon-area ul {
            list-style-type: none;
            padding: 0;
        }

        .icon-area ul li {
            float: left;
            padding: 10px;
            padding-left: 0;
            width: 80px;
        }

        .icon-area ul li i {
            font-size: 18px;
            margin-left: 5px;
            color: #6d6565;
        }

    </style>

{% endblock %}


{% block content %}

    <div class="col-lg-9" style="margin-top: 60px">
        <form action="" method="post" class="form-horizontal">
            {% csrf_token %}

            {% for filed in form_obj %}

                <div class="form-group {% if filed.errors %}has-error{% endif %} ">

                    <label for="{{ filed.id_for_label }}" class="col-sm-2 control-label">{{ filed.label }}</label>
                    <div class="col-sm-10 icon-area">
                        {{ filed }}

                        <span class="help-block">{{ filed.errors.0 }}</span>
                    </div>
                </div>

            {% endfor %}


            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">保存</button>
                </div>
            </div>

        </form>


    </div>

{% endblock %}

rbac/templates/rbac/menu_list.html
{% extends 'layout.html' %}


{% block css %}

    <style>
        .permission-area tr.root {
            background-color: #f1f7fd;;
        }

        .menu-body tr.active {
            background-color: #f1f7fd;
            border-left: 3px solid #fdc00f;
        }


    </style>

{% endblock %}


{% block content %}
    <div style="margin-top: 20px">
        <div class="col-lg-3">
            <div class="panel panel-default ">
                <div class="panel-heading"><i class="fa fa-book"></i> 菜单管理
                    <a href="{% url 'rbac:menu_add' %}" class="btn btn-sm btn-success pull-right"
                       style="padding: 2px 7px;margin-top: -2px"> <i
                            class="fa fa-plus"></i> 新建</a></div>


                <table class="table table-hover ">
                    <thead>
                    <tr>
                        <th>名称</th>
                        <th>图标</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody class="menu-body">
                    {% for menu in all_menus %}
                        <tr class="{% if mid == menu.id|safe %}active{% endif %}">

                            <td><a href="?mid={{ menu.pk }}">{{ menu.name }}</a></td>
                            <td><i class="fa {{ menu.icon }}"></i></td>
                            <td>
                                <a href="{% url 'rbac:menu_edit' menu.pk %}"> <i class="fa  fa-pencil-square-o"></i> </a>
                                <a href="{% url 'rbac:menu_del' 'menu' menu.pk %}" style="color: red;"> <i
                                        class="fa  fa-trash-o"></i> </a>
                            </td>

                        </tr>
                    {% endfor %}


                    </tbody>

                </table>


            </div>

        </div>
        <div class="col-lg-9">
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-cubes"></i> 权限管理
                    <a href="{% url 'rbac:multi_permissions' %}" class="btn btn-sm btn-primary pull-right"
                       style="padding: 2px 7px;margin-top: -2px"> <i
                            class="fa fa-mail-forward"></i> 批量操作</a><a href="{% url 'rbac:permission_add' %}"
                                                                       class="btn btn-sm btn-success pull-right"
                                                                       style="padding: 2px 7px;margin-top: -2px"> <i
                            class="fa fa-plus-circle"></i> 新建</a></div>
                <table class="table table-hover ">
                    <thead>
                    <tr>
                        <th>名称</th>
                        <th>URL</th>
                        <th>URL别名</th>
                        <th>所属菜单</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody class="permission-area">
                    {% for p_permission in all_permissions.values %}
                        <tr class="root" id="{{ p_permission.id }}">
                            <td class="title"><i class="fa fa-caret-down"></i> {{ p_permission.title }}</td>
                            <td>{{ p_permission.url }}</td>
                            <td>{{ p_permission.name }}</td>
                            <td>{{ p_permission.menu.name }}</td>
                            <td>
                                <a href="{% url 'rbac:permission_edit' p_permission.id %}"> <i
                                        class="fa  fa-pencil-square-o"></i> </a>
                                <a href="{% url 'rbac:permission_del' 'permission' p_permission.id %}" style="color: red;">
                                    <i
                                            class="fa  fa-trash-o"></i> </a>
                            </td>

                        </tr>

                        {% for c_permission in p_permission.children %}
                            <tr pid="{{ c_permission.parent_id }}">
                                <td>{{ c_permission.title }}</td>
                                <td>{{ c_permission.url }}</td>
                                <td>{{ c_permission.name }}</td>
                                <td>{{ c_permission.menu.name }}</td>
                                <td>
                                    <a href="{% url 'rbac:permission_edit' c_permission.id %}"> <i
                                            class="fa  fa-pencil-square-o"></i> </a>
                                    <a href="{% url 'rbac:permission_del' 'permission' c_permission.id %}"
                                       style="color: red;"> <i
                                            class="fa  fa-trash-o"></i> </a>
                                </td>

                            </tr>
                        {% endfor %}

                    {% endfor %}


                    </tbody>

                </table>
            </div>
        </div>

    </div>
    {% block js %}

        <script>
            $('.permission-area .root .title').click(function () {
                caret = $(this).find('i');
                tr = $(this).parent();
                id = tr.attr('id');
                if (caret.hasClass('fa-caret-down')) {
                    caret.removeClass('fa-caret-down').addClass('fa-caret-right');
                    tr.nextAll('[pid=' + id + ']').addClass('hide')
                } else {
                    caret.removeClass('fa-caret-right').addClass('fa-caret-down');
                    tr.nextAll('[pid=' + id + ']').removeClass('hide')
                }
            })

        </script>
    {% endblock %}


{% endblock %}

rbac/templates/rbac/multi_permissions.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <form method="post" action="?type=add">
            {% csrf_token %}
            {{ add_formset.management_form }}
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-binoculars" aria-hidden="true"></i> 待新建权限列表
                    <button class="right btn btn-primary btn-xs" style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i>
                        新建
                    </button>
                </div>
                <div class="panel-body" style="color: #9d9d9d;">
                    注意：路由系统中自动发现且数据库中不存在的路由。
                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>URL</th>
                        <th>别名</th>
                        <th>父权限</th>
                        <th>所属菜单</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in add_formset %}

                        <tr>
                            <td style="vertical-align: middle;">{{ forloop.counter }}</td>
                            <td>{{ form.title }} <span>{{ form.title.errors.0 }}</span></td>
                            <td>{{ form.url }}</td>
                            <td>{{ form.name }}</td>
                            <td>{{ form.parent }}</td>
                            <td>{{ form.menu }}</td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <i class="fa fa-th-list" aria-hidden="true"></i> 待删除权限列表
            </div>
            <div class="panel-body" style="color: #9d9d9d;">
                注意：数据库中存在，但路由系统中不存在的路由。
            </div>

            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>名称</th>
                    <th>URL</th>
                    <th>别名</th>
                    <th>父权限</th>
                    <th>所属菜单</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for form in del_formset %}

                    <tr>
                        {{ form.id }}

                        <td style="vertical-align: middle;">{{ forloop.counter }}</td>
                        <td>{{ form.title }} <span>{{ form.title.errors.0 }}</span></td>
                        <td>{{ form.url }}</td>
                        <td>{{ form.name }}</td>
                        <td>{{ form.parent }}</td>
                        <td>{{ form.menu }}</td>
                        <td>
                            <a href="{% url 'rbac:permission_del' 'permission' form.id.value %}" style="color:#d9534f;">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <form method="post" action="?type=update">
            {% csrf_token %}
            {{ update_formset.management_form }}
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-sitemap" aria-hidden="true"></i> 待更新权限列表
                    <button class="right btn btn-primary btn-xs" style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i>
                        更新
                    </button>
                </div>
                <div class="panel-body" style="color: #9d9d9d;">
                    注意：数据库和路由系统都存在的路由。
                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>URL</th>
                        <th>别名</th>
                        <th>父权限</th>
                        <th>所属菜单</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for form in update_formset %}
                        <tr>
                            {{ form.id }}

                            <td style="vertical-align: middle;">{{ forloop.counter }}</td>
                            <td>{{ form.title }} <span>{{ form.title.errors.0 }}</span></td>
                            <td>{{ form.url }}</td>
                            <td>{{ form.name }}</td>
                            <td>{{ form.parent }}</td>
                            <td>{{ form.menu }}</td>
                            <td>
                                <a href="{% url 'rbac:permission_del' 'permission' form.id.value %}"
                                   style="color:#d9534f;">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </form>

    </div>
{% endblock %}

rbac/templates/rbac/role_list.html
{% extends 'layout.html' %}


{% block content %}

    <div style="margin: 20px">

        <a href="{% url 'rbac:role_add' %}" class="btn btn-sm btn-primary">添加</a>
        <table class="table table-hover table-bordered">
            <thead>
            <tr>
                <th>序号</th>
                <th>名称</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for role in all_roles %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ role.name }}</td>
                    <td>
                        <a href="{% url 'rbac:role_edit' role.pk %}"> <i class="fa  fa-pencil-square-o"></i> </a>
                        <a href="{% url 'rbac:role_del' role.pk %}" style="color: red;"> <i class="fa  fa-trash-o"></i> </a>
                    </td>

                </tr>
            {% endfor %}


            </tbody>

        </table>
    </div>


{% endblock %}